### ISSUE TITLE
Investigate xpass failure

### ISSUE THREAD

**Issue by rbillings** [mozilla/Socorro-Tests#322]
Socorro builds are failing due to an xpass which needs investigation.

https://webqa-ci.mozilla.com/view/Socorro/job/socorro.prod.saucelabs/264/HTML_Report/

**Comment by stephendonner** [comment]
Specifically, test_top_crasher_reports_tab_has_uuid_report

**Comment by davehunt** [comment]
An xpass will not cause a job to fail. Socorro *staging* is currently failing due to 6 tests: https://webqa-ci.mozilla.com/view/Socorro/job/socorro.stage.saucelabs/397/HTML_Report/ the linked HTML report in this issue is almost 2 months old. I'll close this, and perhaps a new issue can be opened for the staging failures, if needed.
