### ISSUE TITLE
Migrate from browserid to bidpom

### ISSUE THREAD

**Issue by davehunt** [mozilla/Socorro-Tests#364]
Due to conflicts with another package, the [browserid](https://pypi.python.org/pypi/browserid) package was renamed to [bidpom](https://pypi.python.org/pypi/bidpom/). This suite should be updated to use the new package. This involves changing the dependency name in `requirements.txt` and updating the use of the package to the new package structure. Documentation with examples for bidpom can be found [here](https://github.com/mozilla/bidpom/wiki/Examples-of-integrating-BIDPOM).

This issue is a suitable [Outreachy application contribution](https://github.com/davehunt/pytest-html#outreachy).

**Comment by mun0108** [comment]
I want to take this for outreachy but I am a total newbie and have no idea what to do with the packages.

**Comment by davehunt** [comment]
Hey @mun0108! I've assigned the issue to you. The first thing to do would be see if you can get the tests running locally by following the [README](https://github.com/mozilla/Socorro-Tests/blob/master/README.md). Once you've done that, change the 'browserid' package name in requirements.txt to 'bidpom' and modify the uses of this package to the new package, module and class names. After this, you'll need to confirm that login tests still pass.

**Comment by mun0108** [comment]
I tried running tests locally and got "7 failed, 35 passed, 1 deselected, 2 xpassed, 2 pytest-warnings in 1956.84 seconds". I ran another session and saved the results in an html. I then just changes the 'browserid' package name in requirements.txt to 'bidpom' and right now the test cases are runnig for the same. Now how do I proceed further? What all modifications need to be done? Also about 'Virtualenv and Virtualenvwrapper' - Is there installation important or relevant as it said it was optional.

**Comment by davehunt** [comment]
@mun0108 all tests should pass, so it may be important to know which tests are failing. I'm also interested in what the pytest-warnings were. Perhaps you could run with `-r a` and pastebin the console log? Just changing the package name in `requirements.txt` is not enough. You will then need to remove the `browserid` package from your system and install the `bidpom` package. This can be done using `pip`. The code that uses bidpom is [here](https://github.com/mozilla/Socorro-Tests/blob/21fe84b2957be55058dbacd7eaa0dd6744a80bf6/pages/base_page.py#L213-L215) and it will then need to be updated based on [this example](https://github.com/mozilla/bidpom/wiki/Examples-of-integrating-BIDPOM#sign-in-with-username-and-password-via-the-helper-method).

Without using a virtual environment you will be installing Python packages in your system's default site-packages. This means they're installed globally, and makes it very difficult if you want to work on two project that require different versions of the same package. I highly recommend installing virtualenv, which allows you to have project specific environments with only the necessary packages installed for that project.

**Comment by mun0108** [comment]
Previous time my internet connection was slow , so I think test cases failed because of that. I got a new faster connection this time. :)
I ran the test cases again (for the browserid package) and the results were
{
tests/test_crash_reports.py ....x.............X.........
tests/test_layout.py .....
tests/test_search.py .....
tests/test_smoke_tests.py FE
1 failed, 36 passed, 1 deselected, 1 xfailed, 1 xpassed, 2 pytest-warnings, 1 error in 1076.64 seconds
}
complete result I have pasted here " http://pastebin.com/9JLaPxeD" . Only 1 test case is failing.
The "test_smoke_test.py" is still failing. I ran only this file in quiet mode and still the test case failed. Result I have pasted here: http://pastebin.com/PqjgWuYd .
I also tried running "test_smoke_test.py" in destructive mode and the results were 2 failed, 1 passed, 2 pytest-warnings in 42.15 seconds. I have attached that too here http://pastebin.com/A0fvHcXx .

**Comment by mun0108** [comment]
I created a new testcase file containing only 'test_login_logout' testcase. In that  the "assert csp.footer.is_logged_out" is running fine but failure is occuring just after csp.footer.login() . I wonder if that has anything to do with browserid package installation.

**Comment by mun0108** [comment]
I finally was able to run all the test cases of browserid. And I also learned that initially first time I was getting error because I had installed the bidpom package also. And the 'test_login_logout' was failing beacause the network connection was reset in the college wifi network (I guess some site blocking or something, I don't know). Now I have created virtual environments for both the packages using the virtualenvwrapper.
One more question , (though i don't know if i am heading the right way ) but I think I need to make changes in the whole 'class footer' or just the 'login' function of footer?

**Comment by mun0108** [comment]
Is it okay for me to ask questions here and not in the irc?

**Comment by mun0108** [comment]
I made changes and was able to run all the test cases that were running for browserid are now running for bidpom also. Except for one test case of test_smoke_test.py file i.e. "test_that_bugzilla_link_contain_current_site" which is neither running for browserid and obviously not for bidpom too. I ran all three test cases separately for both browserid and bidpom and only the first test case is failing now. Help me what is going wrong here.

**Comment by davehunt** [comment]
So long as test_login_logout is passing from test_smoke_test.py I think we'll be fine. This suite has a few flaky tests, so I'm not too concerned about getting a 100% pass.

**Comment by davehunt** [comment]
> Is it okay for me to ask questions here and not in the irc?

Yes, however you may get a faster response in IRC.

**Comment by mun0108** [comment]
And where do i need to upload the new test_smoke_test.py file in which the necessary changes were made?

**Comment by davehunt** [comment]
You will need to commit the changes to your fork in a new branch, push them to your GitHub repository, and open a pull request against this repository's master branch.

**Comment by mun0108** [comment]
I have added a commit according to the changes that occured in the repository recently. I also have changed the commit message to "Migrating from browserid to Bidpom -Socorro-Tests #364". And now only one commit is there and I have created a pull request for the same now.
