### ISSUE TITLE
Move the tests into the Socorro project repository

### ISSUE THREAD

**Issue by m8ttyB** [mozilla/Socorro-Tests#405]
Move the tests into https://github.com/mozilla/Socorro
- [x] Test should live in the `e2e-tests/` directory - pr #409 captures this
- [x] Update the readme: use the [fjord project's](https://github.com/mozilla/fjord/blob/master/smoketests/README.rst) readme as a loose outline for an updated readme.
- [x] Update current Jenkins jobs to run with the new project layout.
- [x] Create a pr on the socorro project that includes the tests
- [x] Once the socorro project merges the tests socorro.prod* and socorro.stage* Jenkins jobs should be updated to reflect the change
- [x] After the Jenkins jobs have been updated to use the Socorro repo, depreciate the the Socorro-Tests repository

/cc @peterbe, @willkg, and @adngdb

**Comment by willkg** [comment]
So... I did this with fjord. We can't put it in `tests/ui/` because it's a completely different test suite with a completely different set of requirements and such. With fjord, I stuck it in `smoketests/` off the repository root because in fjord's case, that's all it was doing.

For Socorro, I think we should put it in its own directory just like I did with fjord. `smoketests` or `uitests` or `seleniumisthebesttests` ... something along those lines is fine.

If the tests are enough like fjord's, you could probably crib the README I wrote, too: https://github.com/mozilla/fjord/blob/master/smoketests/README.rst

**Comment by m8ttyB** [comment]
Great points, though these are more than smoke tests, closer to end-to-end tests. @willkg, how do feel about `tests/ui/e2e`?

**Comment by willkg** [comment]
My issue is that they can't be in the `tests/` directory. Any name directory at the top level is fine. If you like, we can call it `cookiedoughicecream/` which I think would have a super handy consequence of everyone wanting to get in on the action.

**Comment by davehunt** [comment]
> once tests have been moved, bouncer.prod* and bouncer.stage* Jenkins jobs should be updated to reflect the change

Was this a typo? What relationship do these tests have with bouncer?

> My issue is that they can't be in the `tests/` directory.

If they're in a subdirectory of tests then they should be able to define their own requirements. Including a pytest configuration file should also indicate it as the root directory for the tests. We could probably bring in tox for running the suite from the top level directory too, which could simplify it further for users.

There doesn't even currently appear to be a top level directory named tests...

**Comment by peterbe** [comment]
The directory can be called whatever "selenium-tests" or "end-to-end-tests" and I think it can go in the root. I strongly encourage hyphenated directories because the project is so Python-heavy, when something has a hyphen in the name it's clear that it's not a working python package, but just a sub directory. Like we do with the "webapp-django" directory.

**Comment by m8ttyB** [comment]
As discussed with the team during the Socorro project meeting, we'll move tests into a `e2e-test/` dir. There are some complexities within the project with currently preclude moving them into a `tests/` dir. This is not to say in the future there won't be an opportunity, for now though, in this issue, we won't resolve that particular puzzle.

**Comment by peterbe** [comment]
Calling something `tests` is best reserved for when the tests are inside a python package. What you're doing is putting the whole *project* into the repo. Not a package. Sure, inside there's a package. But that ought not be mix with things like `./socorro/unittest/` or `./webapp-django/crashstats/*/tests/*`. 

I think `./e2e-tests` is a good name. Go for it.
